### ISSUE TITLE
Выбор языка

### ISSUE THREAD

**Issue by b4kd4u1et** [Bagdaulet02/Mozart#2]
Нужно выбрать язык программирования

**Comment by badcast** [comment]
Предпологаю, можно постороить бэкенд на базе PHP (по моим предположениям, он заточен под это), или как аналог ASP.NET. 
В лучшем случае, можно с нуля построить, выберая ЯП.

**Comment by b4kd4u1et** [comment]
Знаешь php?

**Comment by b4kd4u1et** [comment]
Какие библиотеки и фреймворки имеются у php и asp.net?

**Comment by badcast** [comment]
> Знаешь php?

Да. С PHP знаком, приходилось писать бэкенд.

**Comment by badcast** [comment]
> Какие библиотеки и фреймворки имеются у php и asp.net?
с ASP.NET мало знаком, но знаю, что с ним можно легко проводить отладку, к тому же он поддерживается Microsoft. 


> Предпологаю, можно постороить бэкенд на базе PHP (по моим предположениям, он заточен под это), или как аналог ASP.NET.
В лучшем случае, можно с нуля построить, выберая ЯП.

Эти варианты предложил для проектирования бэкенда. А что касательно fontend под  telegram-api, мало имею опыта. 
У вас есть варианты ?

**Comment by b4kd4u1et** [comment]
Единственная библиотека которую я знаю aiogram для python. Весма удобный.

Там фронтенда особо-то и нет. В телеграме ответы от бота выводиться как сообшения, поетому весь фронтенд это составление сообщении и разных кнопок/команд

**Comment by b4kd4u1et** [comment]
Я одно [тестовое задание](https://github.com/Bagdaulet02/agenda_bot) делал можешь посмотреть как пример

**Comment by badcast** [comment]
> Я одно [тестовое задание](https://github.com/Bagdaulet02/agenda_bot) делал можешь посмотреть как пример

Хорошо. Вечерком изучу.

**Comment by badcast** [comment]
> > Я одно [тестовое задание](https://github.com/Bagdaulet02/agenda_bot) делал можешь посмотреть как пример
> 
> Хорошо. Вечерком изучу.

Изучил, даже провел запуск.

**Comment by b4kd4u1et** [comment]
> > > Я одно [тестовое задание](https://github.com/Bagdaulet02/agenda_bot) делал можешь посмотреть как пример
> > 
> > 
> > Хорошо. Вечерком изучу.
> 
> Изучил, даже провел запуск.

И что думаешь?

**Comment by badcast** [comment]
> > > > Я одно [тестовое задание](https://github.com/Bagdaulet02/agenda_bot) делал можешь посмотреть как пример
> > > 
> > > 
> > > Хорошо. Вечерком изучу.
> > 
> > 
> > Изучил, даже провел запуск.
> 
> И что думаешь?

В целом интересно. python-aiogram используется, что облегчает процесс.

**Comment by b4kd4u1et** [comment]
Может использовать питон? 

Есть желание изучить питон?

**Comment by badcast** [comment]
> Может использовать питон?
> 
> Есть желание изучить питон?

Да. Можно.

**Comment by b4kd4u1et** [comment]
Решено. Будем использовать питон
